version: '3'
services:
  db:
    image: postgres

  web:
    build: .
    command: gunicorn demo.wsgi:application -w9 -b "0.0.0.0:8001" --name app --log-level=debug --log-file=-
    # command: python manage.py runserver 0.0.0.0:8001
    depends_on:
      - db
    ports:
     - "8001:8001"
    volumes:
     - .:/code
